ui            = true
cluster_addr  = "https://127.0.0.1:8201"
api_addr      = "https://127.0.0.1:8200"
disable_mlock = true

storage "raft" {
  path    = "/vault/data"
  node_id = "vault_node_1"
}

listener "tcp" {
  address       = "0.0.0.0:8200"
  tls_cert_file = "/vault/config/full-chain.pem"
  tls_key_file  = "/vault/config/private-key.pem"
}

telemetry {
  disable_hostname = true
}
